# Generated by Django 5.1.3 on 2024-11-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('start', 'Início'), ('end', 'Fim')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=11, null=True)),
                ('destination', models.CharField(blank=True, max_length=11, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['call_id'], name='calls_callr_call_id_de4936_idx')],
                'constraints': [models.UniqueConstraint(fields=('call_id', 'type'), name='unique_call_record_type')],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=11)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('call_record_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_record', to='calls.callrecord')),
                ('call_record_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_record', to='calls.callrecord')),
            ],
        ),
    ]
